language: node_js
node_js:
    - '0.10'

services:
    - elasticsearch

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - gem install compass
    - cd service
    - npm install
    - cd ../static
    - npm install
    - npm install -g bower grunt-cli mocha
    - bower install
    - cd ../

before_script:
    - cd static/app/scripts/
    - cp config.js.example config.js
    - cd ../../../service
    - cp config.js.example config.js
    - cd ../scripts/elastic
    - curl -fsSkL --retry 9 --retry-delay 9 -XPUT 127.0.0.1:9200/_template/template_1 -d @retro_template_es.json
    - curl -fsSkL --retry 9 --retry-delay 9 -XPUT 127.0.0.1:9200/retrospectives_22012014
    - cd ../../

script:
    - cd static
    - npm test
    - cd ../service
    - node app
    - mocha
